### PR TITLE
Moved optic instances to nested class.  Added optic example

### PR DESCRIPTION
**Pull request by mperry**

### CODE REVIEW

**Comment by mperry** [comment]
Addresses #154.

**Comment by orionll** [comment]
Looks fine

**Comment by mperry** [comment]
I still get instability in Stream.bindStackOverflow in the scalacheck tests.  I suspect it is probably related to the Stream and P1 memo implementations.  Not looking forward to looking into this.

**Comment by orionll** [comment]
I think CheckStream can be deleted, because it was already rewritten to Java in StreamProperties.

**Pull request merged**
