### PR TITLE
Implement Bounded typeclass

### PR DESCRIPTION
**Pull request by toxyduck**
#363

### CODE REVIEW

**Comment by EgorKolyshkin** [comment]
Найс тема

**Comment by EgorKolyshkin** [comment]
Заливайте

**Comment by gliptak** [comment]
How is this different from #391?

**Comment by toxyduck** [comment]
@jbgi in #363 asked to separate into two PR's

**Comment by jbgi** [comment]
@yaroslavok well, since all of this PR is in #391 let's close this one.

**Pull request closed without merging**
