### PR TITLE
Split quickcheck property testing into separate module to address #147

### PR DESCRIPTION
**Pull request by mperry**
Address issue #147

### CODE REVIEW

**Comment by mperry** [comment]
@orionll  @jbgi Can you look review this PR please?

**Comment by orionll** [comment]
Everything looks fine.

**Comment by jbgi** [comment]
I think would be more practical if the quickcheck module provide the common Arbitrary instances directly: everyone that use fj would want them.

**Comment by orionll** [comment]
@jbgi What do you mean by "directly"? There are instances for all core classes (arbInteger, arbList, ...) in the Arbitrary class.

**Comment by jbgi** [comment]
oups you are right.

**Comment by jbgi** [comment]
as for naming, maybe 'laws' would be more explicit than 'props'?

**Comment by orionll** [comment]
I'm not sure. There are functor laws, monad laws etc. But are there any laws for List, Seq? Can be the equality `list.reverse().reverse() == list` called a law?

**Comment by jbgi** [comment]
@orionll yes, property is more general than law.
LGTM

**Pull request merged**
