### PR TITLE
Add Lenses - Getter and Setter for immutable data structures

### PR DESCRIPTION
**Pull request by knutwalker**
A Lens is the purely functional alternative for getters and setters.
The implementation is bases one the one provided by scalaz, which
is based on Kmett's Haskell Lenses.

### CODE REVIEW

**Comment by mperry** [comment]
@tonymorris I am not familiar with twanvl lenses, but is this a useful addition given Java's many limitations?  I would imagine a twanvl lens representation would be a lot of extra work if it needed kinds immediately.  

If we changed to twanvl lenses later, how would clients of a lens be affected?

**Comment by jbgi** [comment]
May be the avatar of higher order types as implemented in https://code.google.com/p/highj/ could be a solution? But the verbose generics are a bit repulsive...

**Comment by danieldietrich** [comment]
To get in the direction of higher order types I personally take a naive approach based on generics: https://gist.github.com/danieldietrich/6320d0d617ededbe05f7

I'm using it here for example: http://javaslang.com/javadoc/javaslang/monad/Option.html#flatMap-java.util.function.Function-

**Comment by jbgi** [comment]
@danieldietrich you solution is technically very similar to the one used in highj. Except highj has better separation of concerns, ie List is not required to extends all the "pseudo type-classes" interfaces (foldables and the like). This allows creation of custom "type-classes" in client code.

**Comment by danieldietrich** [comment]
@jbgi thank you for the feedback. I will take a look at highj!

**Comment by mperry** [comment]
I am going to close this PR, since this is addressed by @jbgi in #130 #131 and #132.

**Pull request closed without merging**
